name: Install Poetry on Push

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  install-poetry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
          poetry --version