name: Install Poetry on Push

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  install-poetry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          pip3 install poetry
          poetry --version
          poetry install
          poetry build
          ls -l dist
      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(grep "version =" pyproject.toml | awk '{print $3}' | tr -d '"')
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/console-${{ steps.extract_version.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          